name: Docker CI/CD
on: [push, pull_request]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Docker Image
      run: docker build -t vinay-devops-app .
    - name: Test Endpoints
      run: |
        docker run --rm -p 3000:3000 vinay-devops-app &
        sleep 5
        curl -f http://localhost:3000 || exit 1
        curl -f http://localhost:3000/health || exit 1
